<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/01/28 19:33:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'jobeet',
  'password' => 'jobeet',
  'name' => 'doctrine',
)),);
